swagger: '2.0'
info:
  version: 1.0.0
  title: GoogleCalendar-API-docs
  description: GoogleCalendar API문서
  servers:
    - description: GoogleCalendar-Clone API
      url: 'http://158.247.214.79/'
    - description: GoogleCalendar-Clone dev
      url: 'http://localhost:80/'
tags:
  - name: user
    description: API about user
  - name: privateEvent
    description: API about privateEvent
  - name: calendar
    description: API about calendar
  - name: event
    description: API about event
  - name: alert
    description: API about alert
paths:
  /api/user/signup:
    post:
      tags:
        - user
      summary: 회원가입
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              nickname:
                type: string
      responses:
        '200':
          description: 성공
          schema:
            properties:
              success:
                type: boolean
                example: true
        '401':
          description: 이메일 중복
          schema:
            properties:
              message:
                type: string
                example: 이미 사용중인 이메일 입니다!
        '402':
          description: 닉네임 중복
          schema:
            properties:
              message:
                type: string
                example: 이미 사용중인 닉네임 입니다!
        '500':
          $ref: '#/commonError'
  /api/user/signin:
    post:
      tags:
        - user
      summary: 로그인
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: 성공
          schema:
            properties:
              userData:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  nickname:
                    type: string
                  checkedCalendar:
                    type: string
                  ProfileImages:
                    type: object
                    properties:
                      src:
                        type: string
                  refreshToken:
                    type: string
                  accessToken:
                    type: string
        '401':
          description: 존재하지 않는 유저 (이메일이 틀린 경우)
          schema:
            properties:
              message:
                type: string
                example: 유저가 존재하지 않습니다!
        '402':
          description: 비밀번호 일치하지 않음 (이메일은 맞지만 비밀번호가 틀린 경우)
          schema:
            properties:
              message:
                type: string
                example: 패스워드가 일치하지 않습니다!
        '500':
          $ref: '#/commonError'
  /api/user/checkedCalendar:
    post:
      tags:
        - user
      summary: 달력 체킹 수정
      parameters:
        - name: Authorization
          in: header
          required: true
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              checkedList:
                type: string
      responses:
        '200':
          description: 성공
          schema:
            properties:
              success:
                type: boolean
                example: true
  /api/calendar/signup:
    post:
      tags:
        - calendar
      summary: 회원가입
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              nickname:
                type: string
      responses:
        '200':
          description: 성공
          schema:
            properties:
              success:
                type: boolean
                example: true
        '401':
          description: 이메일 중복
          schema:
            properties:
              message:
                type: string
                example: 이미 사용중인 이메일 입니다!
        '402':
          description: 닉네임 중복
          schema:
            properties:
              message:
                type: string
                example: 이미 사용중인 닉네임 입니다!
        '500':
          $ref: '#/commonError'
commonError:
  description: 중복 에러
  schema:
    properties:
      message:
        type: string
        example: 중복에러
